-- Таблица товаров
create table product (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(255) NOT NULL,
    picture_url VARCHAR(255)
);

-- Дополнительная инфа о товарах
create table product_info (
    product_id  BIGINT       NOT NULL,
    name        VARCHAR(255) NOT NULL,
    price       DOUBLE PRECISION
);

-- Таблица заказов
create table orders (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    status      VARCHAR(255)
);

-- Таблица с датами заказов
create table orders_date (
    order_id    BIGINT       NOT NULL,
    status      VARCHAR(255),
    date_created DATE        DEFAULT CURRENT_DATE
);

-- Таблица состава заказов
create table order_product (
    quantity    INTEGER      NOT NULL,
    order_id    BIGINT       NOT NULL,
    product_id  BIGINT       NOT NULL
);